# Generated by Django 5.1 on 2024-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pages', models.IntegerField(default=0)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
